export type {
  ApiErrorBody,
  ApiErrorResponse,
  ApiResponse,
  ApiSuccessResponse,
  ArtikelAuthorRef,
  ArtikelCategoryRef,
  ArtikelDetail,
  ArtikelListItem,
  ArtikelListParams,
  ArtikelListResult,
  HealthData,
  PaginationMeta,
  ProgramDetail,
  ProgramListItem,
  KategoriRef,
  KegiatanListItem,
  KegiatanDetail,
  KegiatanListParams,
  KegiatanListResult,
  KegiatanWritePayload,
  EventRef,
  AgendaListItem,
  AgendaListParams,
  AgendaListResult,
  AgendaWritePayload,
  GaleriImageItem,
  GaleriListItem,
  GaleriListParams,
  GaleriListResult,
  GaleriWritePayload,
  BannerWritePayload,
  PengurusWritePayload,
  ProgramWritePayload,
  DokumenWritePayload,
  SettingsData,
  SettingsStats,
  SettingsSocialMedia,
  BannerListItem,
  PengurusListItem,
  TestimoniListItem,
  DokumenListItem,
  DokumenListParams,
  DokumenListResult,
  ContactSubmitData,
  AuthRole,
  AuthUser,
  LoginPayload,
  LoginResult,
  DashboardStats,
  KategoriItem,
  ArtikelWritePayload,
  UploadResult,
} from "./api";
export type { Artikel, ArtikelStatus, Kategori, KategoriType } from "./artikel";
export type { Dokumen } from "./dokumen";
export type { Agenda, Kegiatan, KegiatanStatus } from "./kegiatan";
export type { Banner, Pengurus, Program, Testimoni } from "./program";
export type { Galeri, GaleriImage, SiteSettings, SiteStats, SocialMedia } from "./settings";
