import { Router } from "express";
import artikelRoutes from "./artikel.routes";
import authRoutes from "./auth.routes";
import bannerRoutes from "./banner.routes";
import contactRoutes from "./contact.routes";
import dashboardRoutes from "./dashboard.routes";
import dokumenRoutes from "./dokumen.routes";
import donasiRoutes from "./donasi.routes";
import galeriRoutes from "./galeri.routes";
import healthRoutes from "./health.routes";
import kategoriRoutes from "./kategori.routes";
import kegiatanRoutes from "./kegiatan.routes";
import pengurusRoutes from "./pengurus.routes";
import programRoutes from "./program.routes";
import searchRoutes from "./search.routes";
import settingsRoutes from "./settings.routes";
import testimoniRoutes from "./testimoni.routes";
import uploadRoutes from "./upload.routes";
import usersRoutes from "./users.routes";

const router = Router();

router.use(healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/artikel", artikelRoutes);
router.use("/kategori", kategoriRoutes);
router.use("/kegiatan", kegiatanRoutes);
router.use("/galeri", galeriRoutes);
router.use("/banner", bannerRoutes);
router.use("/pengurus", pengurusRoutes);
router.use("/program", programRoutes);
router.use("/testimoni", testimoniRoutes);
router.use("/dokumen", dokumenRoutes);
router.use("/donasi", donasiRoutes);
router.use("/contact", contactRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/search", searchRoutes);
router.use("/settings", settingsRoutes);
router.use("/upload", uploadRoutes);

export default router;
